import { BROWSER_INTERACTION_TOOL_DEFINITIONS } from './interaction';
import { BROWSER_KEYBOARD_MOUSE_TOOL_DEFINITIONS } from './keyboard-mouse';
import { BROWSER_NAVIGATION_TOOL_DEFINITIONS } from './navigation';
import { BROWSER_OBSERVATION_TOOL_DEFINITIONS } from './observation';

export const BROWSER_TOOL_DEFINITIONS = [
  ...BROWSER_OBSERVATION_TOOL_DEFINITIONS,
  ...BROWSER_NAVIGATION_TOOL_DEFINITIONS,
  ...BROWSER_INTERACTION_TOOL_DEFINITIONS,
  ...BROWSER_KEYBOARD_MOUSE_TOOL_DEFINITIONS,
] as const;

export {
  BROWSER_INTERACTION_TOOL_DEFINITIONS,
  BROWSER_KEYBOARD_MOUSE_TOOL_DEFINITIONS,
  BROWSER_NAVIGATION_TOOL_DEFINITIONS,
  BROWSER_OBSERVATION_TOOL_DEFINITIONS,
};
