export const ASSISTANT_INTERACTIVE_QUEUE = 'assistant-interactive';
export const ASSISTANT_BACKGROUND_QUEUE = 'assistant-background';
export const EXECUTE_ASSISTANT_JOB = 'execute-assistant';

export const ASSISTANT_WORKER_CONCURRENCY = 5;
export const ASSISTANT_WORKER_MAX_CONCURRENCY = 10;
export const ASSISTANT_BACKGROUND_WORKER_CONCURRENCY = 2;
export const ASSISTANT_MAX_ACTIVE_SHORT_RUNS_PER_USER = 2;
export const ASSISTANT_MAX_ACTIVE_LONG_RUNS_PER_USER = 1;
export const ASSISTANT_MAX_QUEUED_RUNS_PER_USER = 10;
export const ASSISTANT_USER_SLOT_RETRY_DELAY = 1_000;
